---
- name: Install Packages
  apt: pkg={{ item }} state=present
  become: yes
  become_method: sudo
  with_items:
    - php5
    - php5-common
    - php5-cli

- name: Install PHP extensions (modules)
  apt: pkg={{ item.value }}
  become: yes
  become_method: sudo
  with_dict: "{{ php.modules }}"

- name: Enable extensions (modules) for all SAPI's
  command: php5enmod -s ALL {{ item.key }}
  become: yes
  become_method: sudo
  with_dict: "{{ php.modules }}"
